// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7yRDrtVYa7HUIWZ8PbKomOk7F8XCHLs',
    appId: '1:705212637904:web:31a3c24193868bf376f4d5',
    messagingSenderId: '705212637904',
    projectId: 'evently-62176',
    authDomain: 'evently-62176.firebaseapp.com',
    storageBucket: 'evently-62176.firebasestorage.app',
    measurementId: 'G-SWBWWQ3EK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACEc3r5bUmby5227Omn6x_ADCGL7xt2wU',
    appId: '1:705212637904:android:348de2b530c1720476f4d5',
    messagingSenderId: '705212637904',
    projectId: 'evently-62176',
    storageBucket: 'evently-62176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcoRaqgEd-20pUBFt41wn1FMfeHnb5D-U',
    appId: '1:705212637904:ios:d2c436c6f9ca68dd76f4d5',
    messagingSenderId: '705212637904',
    projectId: 'evently-62176',
    storageBucket: 'evently-62176.firebasestorage.app',
    iosClientId: '705212637904-vusbm63asec2059nno2melvo0h3tenia.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

}